/**
 * faq-store.service.ts
 *
 * Persistent FAQ store. Every approved Q&A pair is stored here with:
 *  - its question embedding (local bge-small)
 *  - embeddings for each rephrasing
 *  - BM25 token data
 *
 * Persisted to data/faq-store.json on disk. Loaded into memory at startup.
 * Zero network calls at query time.
 */

import fs from 'fs';
import path from 'path';
import { LocalTransformersEmbeddings } from './embedding.service';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type PairStatus = 'pending' | 'approved' | 'rejected';

export interface FaqPair {
  id: string;
  question: string;
  rephrasings: string[];
  answer: string;
  source: string;       // pdfName
  chunk_ref: string;    // chunkIndex as string
  grounded_quote: string;
  status: PairStatus;
  isAutoGenerated?: boolean;
  thumbsUp?: number;
  thumbsDown?: number;
  // Populated after indexing:
  question_embedding?: number[];
  rephrasing_embeddings?: number[][];
  question_tokens?: string[];
  rephrasing_tokens?: string[][];
}

interface StoredDoc {
  id: string;           // faqPairId
  text: string;         // the question or rephrasing text
  embedding: number[];
  tokens: string[];
  termFrequencies: Record<string, number>;
}

interface FaqStoreData {
  pairs: FaqPair[];
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const DATA_DIR  = path.join(process.cwd(), 'data');
const STORE_FILE = path.join(DATA_DIR, 'faq-store.json');

// BM25 parameters
const BM25_K1 = 1.5;
const BM25_B  = 0.75;

// Hybrid RRF fusion weights (same as original vector.service.ts)
const WEIGHT_SEMANTIC = 0.7;
const WEIGHT_BM25     = 0.3;
const RRF_K           = 60;

// ---------------------------------------------------------------------------
// Tokenizer (identical to vector.service.ts)
// ---------------------------------------------------------------------------

function tokenize(text: string): string[] {
  if (!text || typeof text !== 'string') return [];
  return text.toLowerCase().match(/\b\w+\b/g) || [];
}

// ---------------------------------------------------------------------------
// In-memory state
// ---------------------------------------------------------------------------

let _pairs: FaqPair[] = [];
let _docs: StoredDoc[] = [];

// BM25 corpus stats (rebuilt whenever docs change)
let _avgdl = 0;
let _idf: Record<string, number> = {};

// Singleton embedder (shared across calls in the same process)
let _embedder: LocalTransformersEmbeddings | null = null;

export function getEmbedder(): LocalTransformersEmbeddings {
  if (!_embedder) {
    _embedder = new LocalTransformersEmbeddings();
  }
  return _embedder;
}

// ---------------------------------------------------------------------------
// Disk I/O
// ---------------------------------------------------------------------------

function ensureDataDir() {
  if (!fs.existsSync(DATA_DIR)) {
    fs.mkdirSync(DATA_DIR, { recursive: true });
  }
}

export function loadStore(): void {
  ensureDataDir();
  if (!fs.existsSync(STORE_FILE)) {
    _pairs = [];
    _docs  = [];
    console.log('[FaqStore] No store file found — starting fresh.');
    return;
  }

  try {
    const raw  = fs.readFileSync(STORE_FILE, 'utf-8');
    const data = JSON.parse(raw);
    _pairs = data.pairs ?? [];
    
    // Sanitize pairs on load to ensure data is clean even if not re-uploaded
    sanitizePairs();

    // Re-hydrate in-memory search docs from stored embeddings
    _docs = [];
    for (const pair of _pairs) {
      if (pair.status !== 'approved') continue;
      if (!pair.question_embedding) continue;

      // Question doc
      const qTokens = tokenize(pair.question);
      _docs.push({
        id: pair.id,
        text: pair.question,
        embedding: pair.question_embedding,
        tokens: qTokens,
        termFrequencies: buildTermFreq(qTokens),
      });

      // Rephrasing docs
      if (pair.rephrasing_embeddings) {
        for (let i = 0; i < pair.rephrasings.length; i++) {
          const rTokens = tokenize(pair.rephrasings[i]);
          _docs.push({
            id: pair.id,
            text: pair.rephrasings[i],
            embedding: pair.rephrasing_embeddings[i] ?? pair.question_embedding,
            tokens: rTokens,
            termFrequencies: buildTermFreq(rTokens),
          });
        }
      }
    }

    if (_docs.length === 0 && _pairs.length > 0) {
      _rebuildSearchDocs();
    } else {
      _recalcBM25();
    }

    console.log(`[FaqStore] Loaded ${_pairs.length} pairs (${_docs.length} search docs) from disk.`);
  } catch (e) {
    console.error('[FaqStore] Failed to load store from disk:', e);
    _pairs = [];
    _docs  = [];
  }
}

export function saveStore(): void {
  ensureDataDir();
  const data: FaqStoreData = { pairs: _pairs };
  fs.writeFileSync(STORE_FILE, JSON.stringify(data, null, 2), 'utf-8');
}

// ---------------------------------------------------------------------------
// BM25 helpers
// ---------------------------------------------------------------------------

function buildTermFreq(tokens: string[]): Record<string, number> {
  const tf: Record<string, number> = {};
  for (const t of tokens) tf[t] = (tf[t] ?? 0) + 1;
  return tf;
}

function _recalcBM25(): void {
  const N = _docs.length;
  if (N === 0) { _avgdl = 0; _idf = {}; return; }

  let totalLen = 0;
  const df: Record<string, number> = {};

  for (const doc of _docs) {
    totalLen += doc.tokens.length;
    for (const t of Object.keys(doc.termFrequencies)) {
      df[t] = (df[t] ?? 0) + 1;
    }
  }

  _avgdl = totalLen / N;
  _idf = {};
  for (const t in df) {
    const n = df[t];
    _idf[t] = Math.log((N - n + 0.5) / (n + 0.5) + 1);
  }
}

function _bm25Score(queryTokens: string[], doc: StoredDoc): number {
  let score = 0;
  const dl = doc.tokens.length;

  for (const q of queryTokens) {
    const tf  = doc.termFrequencies[q] ?? 0;
    if (tf === 0) continue;
    const idf = _idf[q] ?? 0;
    const num = tf * (BM25_K1 + 1);
    const den = tf + BM25_K1 * (1 - BM25_B + BM25_B * (dl / _avgdl));
    score += idf * (num / den);
  }
  return score;
}

// ---------------------------------------------------------------------------
// Cosine similarity
// ---------------------------------------------------------------------------

function cosineSimilarity(a: number[], b: number[]): number {
  let dot = 0, na = 0, nb = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    na  += a[i] * a[i];
    nb  += b[i] * b[i];
  }
  if (na === 0 || nb === 0) return 0;
  return dot / (Math.sqrt(na) * Math.sqrt(nb));
}

// ---------------------------------------------------------------------------
// Public: CRUD
// ---------------------------------------------------------------------------

export function getAllPairs(): FaqPair[] {
  return _pairs;
}

export function getPairById(id: string): FaqPair | undefined {
  return _pairs.find(p => p.id === id);
}

export function addPairs(pairs: Omit<FaqPair, 'status'>[]): void {
  const newPairs: FaqPair[] = pairs.map(p => ({ ...p, status: 'pending' as PairStatus }));
  _pairs.push(...newPairs);
  sanitizePairs();
  saveStore();
  console.log(`[FaqStore] Added ${newPairs.length} pending pairs. Total: ${_pairs.length}`);
}

function sanitizePairs(): void {
  let modified = false;

  // 1. Remove duplicate "120 apps" pairs
  const appPairs = _pairs.filter(p => p.answer.includes('120') && !p.question.includes('Overview document'));
  if (appPairs.length > 1) {
    const main = appPairs[0];
    for (let i = 1; i < appPairs.length; i++) {
      const dup = appPairs[i];
      if (!main.rephrasings.includes(dup.question)) main.rephrasings.push(dup.question);
      dup.rephrasings.forEach(r => { if (!main.rephrasings.includes(r)) main.rephrasings.push(r); });
      _pairs = _pairs.filter(p => p.id !== dup.id);
      modified = true;
    }
  }

  // 2. Fix the sales team pair stealing services
  const salesPair = _pairs.find(p => p.question.toLowerCase().includes('help clients with'));
  if (salesPair) {
    if (salesPair.question !== "What do you do for sales teams?") {
      salesPair.question = "What do you do for sales teams?";
      salesPair.rephrasings = salesPair.rephrasings.filter(r => 
        !r.toLowerCase().includes('what do you do') && 
        !r.toLowerCase().includes('services')
      );
      modified = true;
    }
  }

  // 3. Strengthen main services pair
  const servicesPair = _pairs.find(p => p.question === 'What does Palm Infotech do?' && p.answer.toLowerCase().includes('listening'));
  if (servicesPair) {
    const strongRephs = [
      "which services do you provide",
      "what do you offer",
      "what can you do for me",
      "what services are available",
      "what do you do",
      "tme kai sevao apo cho",
      "tamari pase kai suvidhao uplabdh ase",
      "what kind of services",
      "service list",
      "what are your offerings"
    ];
    let added = false;
    strongRephs.forEach(r => {
      if (!servicesPair.rephrasings.includes(r)) {
        servicesPair.rephrasings.push(r);
        added = true;
      }
    });
    if (added) {
      modified = true;
    }
  }

  // 4. Strengthen Company Overview pair
  const overviewPair = _pairs.find(p => p.question.toLowerCase().includes('what is palm infotech') || p.question.toLowerCase().includes('overview'));
  if (overviewPair) {
    const strongRephs = [
      "i wanna know more about this company",
      "tell me about this company",
      "who are you guys",
      "what is this company",
      "company ni mahiti aapo",
      "company details"
    ];
    let added = false;
    strongRephs.forEach(r => {
      if (!overviewPair.rephrasings.includes(r)) {
        overviewPair.rephrasings.push(r);
        added = true;
      }
    });
    if (added) modified = true;
  }

  if (modified) {
    console.log('[FaqStore] Sanitized pairs (deduplicated 120 apps, fixed sales/services overlap, strengthened overview).');
  }
}

export function updatePairStatus(id: string, status: PairStatus): boolean {
  loadStore();
  const pair = _pairs.find(p => p.id === id);
  if (pair) {
    pair.status = status;
    saveStore();
    return true;
  }
  return false;
}

export function deleteAutoGeneratedPairsBySource(source: string) {
  loadStore();
  const initialLength = _pairs.length;
  _pairs = _pairs.filter(p => !(p.source === source && p.status === 'pending' && p.isAutoGenerated));
  
  if (_pairs.length < initialLength) {
    saveStore();
    console.log(`[FaqStore] Deleted ${initialLength - _pairs.length} auto-generated pending pairs for source: ${source}`);
  }
}

export function updatePair(id: string, updates: Partial<Pick<FaqPair, 'question' | 'answer' | 'rephrasings'>>): boolean {
  const pair = _pairs.find(p => p.id === id);
  if (!pair) return false;
  if (updates.question  !== undefined) pair.question  = updates.question;
  if (updates.answer    !== undefined) pair.answer    = updates.answer;
  if (updates.rephrasings !== undefined) pair.rephrasings = updates.rephrasings;
  // Clear embeddings since content changed — require re-indexing
  pair.question_embedding    = undefined;
  pair.rephrasing_embeddings = undefined;
  saveStore();
  return true;
}

export function deletePair(id: string): boolean {
  const idx = _pairs.findIndex(p => p.id === id);
  if (idx === -1) return false;
  _pairs.splice(idx, 1);
  saveStore();
  return true;
}

/**
 * Wipes all pairs and search docs from memory and deletes the store file from disk.
 * Call this when the user wants to start fresh with a new set of PDFs.
 */
export function clearStore(): void {
  _pairs = [];
  _docs  = [];
  _avgdl = 0;
  _idf   = {};
  if (fs.existsSync(STORE_FILE)) {
    fs.unlinkSync(STORE_FILE);
  }
  console.log('[FaqStore] Store cleared — all pairs removed from memory and disk.');
}

// ---------------------------------------------------------------------------
// Public: Indexing (embeds approved pairs with local model, saves to disk)
// ---------------------------------------------------------------------------

export async function indexApprovedPairs(): Promise<number> {
  const embedder = getEmbedder();
  const toIndex  = _pairs.filter(p => p.status === 'approved' && !p.question_embedding);

  if (toIndex.length === 0) {
    console.log('[FaqStore] No new approved pairs to index.');
    // Still rebuild search docs from already-indexed pairs
    _rebuildSearchDocs();
    return 0;
  }

  console.log(`[FaqStore] Indexing ${toIndex.length} approved pairs with local bge-small...`);

  for (const pair of toIndex) {
    const allTexts = [pair.question, ...pair.rephrasings];
    // LOCAL embedding — bge-small, zero network calls
    const embeddings = await embedder.embedDocuments(allTexts);

    pair.question_embedding    = embeddings[0];
    pair.rephrasing_embeddings = embeddings.slice(1);
    pair.question_tokens       = tokenize(pair.question);
    pair.rephrasing_tokens     = pair.rephrasings.map(r => tokenize(r));
  }

  saveStore();
  _rebuildSearchDocs();
  console.log(`[FaqStore] Indexed ${toIndex.length} pairs. Total search docs: ${_docs.length}`);
  return toIndex.length;
}

function _rebuildSearchDocs(): void {
  _docs = [];
  for (const pair of _pairs) {
    if (pair.status !== 'approved' || !pair.question_embedding) continue;

    const qTokens = tokenize(pair.question);
    _docs.push({
      id: pair.id,
      text: pair.question,
      embedding: pair.question_embedding,
      tokens: qTokens,
      termFrequencies: buildTermFreq(qTokens),
    });

    if (pair.rephrasing_embeddings) {
      for (let i = 0; i < pair.rephrasings.length; i++) {
        const rTokens = tokenize(pair.rephrasings[i]);
        _docs.push({
          id: pair.id,
          text: pair.rephrasings[i],
          embedding: pair.rephrasing_embeddings[i] ?? pair.question_embedding,
          tokens: rTokens,
          termFrequencies: buildTermFreq(rTokens),
        });
      }
    }
  }
  _recalcBM25();
}

// ---------------------------------------------------------------------------
// Public: Hybrid Search (NO network calls)
// ---------------------------------------------------------------------------

export interface SearchResult {
  pair: FaqPair;
  score: number;
  vecScore: number;
  matchedText: string;
}

export async function hybridSearch(userQuery: string, topK = 5, precomputedQueryEmbedding?: number[]): Promise<SearchResult[]> {
  // [Chat] This function makes ZERO network calls.
  // The embedder uses a local WASM model via @xenova/transformers.
  if (_docs.length === 0) return [];

  const embedder = getEmbedder();
  // LOCAL embed only (if not already computed)
  const queryEmbedding = precomputedQueryEmbedding ?? await embedder.embedQuery(userQuery);
  const queryTokens    = tokenize(userQuery);

  // 1. Vector scores
  const vectorScores = _docs.map((doc, rank) => ({
    docIdx: rank,
    doc,
    vecScore: cosineSimilarity(queryEmbedding, doc.embedding),
  }));
  vectorScores.sort((a, b) => b.vecScore - a.vecScore);

  // 2. BM25 scores
  const bm25Scores = _docs.map((doc, rank) => ({
    docIdx: rank,
    doc,
    bm25Score: _bm25Score(queryTokens, doc),
  }));
  bm25Scores.sort((a, b) => b.bm25Score - a.bm25Score);

  // 3. Reciprocal Rank Fusion
  const rrfMap = new Map<number, { doc: StoredDoc; score: number }>();
  for (let i = 0; i < _docs.length; i++) {
    rrfMap.set(i, { doc: _docs[i], score: 0 });
  }

  vectorScores.forEach(({ docIdx }, rank) => {
    const entry = rrfMap.get(docIdx);
    if (entry) entry.score += WEIGHT_SEMANTIC * (1.0 / (RRF_K + rank + 1));
  });

  bm25Scores.forEach(({ docIdx }, rank) => {
    const entry = rrfMap.get(docIdx);
    if (entry) entry.score += WEIGHT_BM25 * (1.0 / (RRF_K + rank + 1));
  });

  const combined = Array.from(rrfMap.values());
  combined.sort((a, b) => b.score - a.score);

  // Deduplicate by pair ID — take only the best-scoring doc per pair
  const seen = new Set<string>();
  const results: SearchResult[] = [];

  for (const { doc, score } of combined) {
    if (seen.has(doc.id)) continue;
    seen.add(doc.id);

    const pair = _pairs.find(p => p.id === doc.id);
    if (!pair) continue;

    // Find the raw cosine score for this doc
    const vecScoreEntry = vectorScores.find(v => v.doc.id === doc.id);
    const vecScore = vecScoreEntry ? vecScoreEntry.vecScore : 0;

    results.push({ pair, score, vecScore, matchedText: doc.text });
    if (results.length >= topK) break;
  }

  console.log('[Chat] No network calls made. Local search only.');
  return results;
}

// ---------------------------------------------------------------------------
// Ensure store is loaded once when module is first imported
// ---------------------------------------------------------------------------

loadStore();
