/**
 * api/upload/route.ts
 *
 * Upload pipeline with vision fallback for design-heavy / custom-font PDFs:
 *
 *  1. Save PDF to disk (kept until all pages processed)
 *  2. Extract text per page (pdf.service.ts)
 *  3a. Text pages  → chunk → OpenAI text  → grounding check → FAQ pairs
 *  3b. Image pages → render PNG → OpenAI vision → FAQ pairs (no grounding check)
 *  4. Empty-doc guard: if 0 pairs from BOTH paths → return 422, skip overview
 *  5. Document-level overview pairs (only when content exists)
 *  6. Write all passing pairs to faq-store with status: "pending"
 *
 * OpenAI is NOT called at chat time — only here, once per upload.
 */

import { NextRequest, NextResponse } from 'next/server';
import {
  extractTextFromPDF,
  splitPDFText,
  renderPageToImageBuffer,
} from '@/services/pdf.service';
import {
  generateFaqPairs,
  generateFaqPairsFromImage,
  generateDocumentOverviewPairs,
  type RawPair,
} from '@/services/openai.service';
import { addPairs, loadStore, deleteAutoGeneratedPairsBySource } from '@/services/faq-store.service';
import { addChunksToStore, deleteChunksBySource } from '@/services/vector.service';
import fs from 'fs';
import path from 'path';
import { v4 as uuidv4 } from 'uuid';

// ---------------------------------------------------------------------------
// Grounding check (only for text-sourced pairs)
// ---------------------------------------------------------------------------

function normalizeWS(s: string): string {
  return s.replace(/\s+/g, ' ').trim();
}

function isGrounded(quote: string, chunkText: string): boolean {
  if (!quote || quote.trim().length < 5) return false;
  return normalizeWS(chunkText).includes(normalizeWS(quote));
}

// ---------------------------------------------------------------------------
// POST handler
// ---------------------------------------------------------------------------

export const maxDuration = 300; // Allow up to 5 min for large PDFs (Vercel)

export async function POST(req: NextRequest) {
  try {
    loadStore();

    const formData = await req.formData();
    const files = formData.getAll('files') as File[];

    if (!files || files.length === 0) {
      return NextResponse.json({ error: 'No files provided' }, { status: 400 });
    }

    if (files.length > 50) {
      return NextResponse.json({ error: 'Maximum 50 PDFs allowed' }, { status: 400 });
    }

    const uploadDir = path.join(process.cwd(), 'uploads');
    if (!fs.existsSync(uploadDir)) fs.mkdirSync(uploadDir, { recursive: true });

    let totalPairsGenerated = 0;
    let totalPairsGrounded  = 0;
    let totalPairsFailed    = 0;

    for (const file of files) {
      if (!file.name.endsWith('.pdf')) continue;

      console.log(`[Upload] Processing "${file.name}"...`);
      deleteAutoGeneratedPairsBySource(file.name);
      await deleteChunksBySource(file.name);

      // -----------------------------------------------------------------------
      // 1. Save to disk (kept for image rendering; deleted after all pages done)
      // -----------------------------------------------------------------------
      const bytes    = await file.arrayBuffer();
      const buffer   = Buffer.from(bytes);
      const fileName = `${uuidv4()}-${file.name}`;
      const filePath = path.join(uploadDir, fileName);

      fs.writeFileSync(filePath, buffer);

      // -----------------------------------------------------------------------
      // 2. Extract text per page (includes isImageOnly flag per page)
      // -----------------------------------------------------------------------
      const pagesText = await extractTextFromPDF(filePath);

      const imageOnlyPages = pagesText.filter(p => p.isImageOnly);
      const textPages      = pagesText.filter(p => !p.isImageOnly);

      console.log(
        `[Upload] "${file.name}" — ${textPages.length} text pages, ` +
        `${imageOnlyPages.length} image-only pages (vision fallback).`
      );

      // -----------------------------------------------------------------------
      // 3a. Text path: chunk → OpenAI text → grounding check
      // -----------------------------------------------------------------------
      const pairsForStore: Omit<import('@/services/faq-store.service').FaqPair, 'status'>[] = [];
      const allChunkTexts: string[] = [];

      const chunks = await splitPDFText(textPages, file.name);
      
      if (chunks.length > 0) {
        await addChunksToStore(chunks);
      }

      for (const chunk of chunks) {
        const chunkText: string = chunk.pageContent;
        allChunkTexts.push(chunkText);

        let rawPairs: RawPair[] = [];
        try {
          rawPairs = await generateFaqPairs(chunkText);
        } catch (e: any) {
          console.error(`[Upload] OpenAI text call failed for chunk ${chunk.metadata.chunkIndex}:`, e?.message);
          continue;
        }

        totalPairsGenerated += rawPairs.length;

        for (const raw of rawPairs) {
          if (isGrounded(raw.grounded_quote, chunkText)) {
            pairsForStore.push({
              id:             uuidv4(),
              question:       raw.question,
              rephrasings:    raw.rephrasings,
              answer:         raw.answer,
              source:         file.name,
              chunk_ref:      String(chunk.metadata.chunkIndex),
              grounded_quote: raw.grounded_quote,
            });
            totalPairsGrounded++;
          } else {
            console.warn(
              `[Upload][Grounding] FAILED — pair excluded. ` +
              `Q: "${raw.question.slice(0, 60)}..." | ` +
              `Quote not found in chunk ${chunk.metadata.chunkIndex}.`
            );
            totalPairsFailed++;
          }
        }
      }

      // -----------------------------------------------------------------------
      // 3b. Vision path: render page → GPT-4o vision → pairs (no grounding check)
      // -----------------------------------------------------------------------
      for (const page of imageOnlyPages) {
        let imageBuffer: Buffer;
        try {
          imageBuffer = await renderPageToImageBuffer(filePath, page.pageNumber);
        } catch (e: any) {
          console.error(`[Upload] Page render failed for page ${page.pageNumber}:`, e?.message);
          continue;
        }

        let rawPairs: RawPair[] = [];
        try {
          rawPairs = await generateFaqPairsFromImage(imageBuffer, page.pageNumber);
        } catch (e: any) {
          console.error(`[Upload] OpenAI vision call failed for page ${page.pageNumber}:`, e?.message);
          continue;
        }

        totalPairsGenerated += rawPairs.length;

        for (const raw of rawPairs) {
          // Vision pairs: no verbatim source text to check against — accept all
          pairsForStore.push({
            id:             uuidv4(),
            question:       raw.question,
            rephrasings:    raw.rephrasings,
            answer:         raw.answer,
            source:         file.name,
            chunk_ref:      `vision-p${page.pageNumber}`,
            grounded_quote: raw.grounded_quote ?? '',
          });
          totalPairsGrounded++;
        }
      }

      // -----------------------------------------------------------------------
      // Clean up temp file — no longer needed after all pages processed
      // -----------------------------------------------------------------------
      fs.unlinkSync(filePath);

      // -----------------------------------------------------------------------
      // 4. Empty-doc guard: if both paths produced nothing, abort this file
      // -----------------------------------------------------------------------
      if (pairsForStore.length === 0) {
        console.error(
          `[Upload] "${file.name}" — 0 pairs from text AND vision paths. ` +
          `PDF could not be read. Skipping overview generation.`
        );
        return NextResponse.json(
          {
            error: `PDF could not be read — no text or content was extracted from "${file.name}". ` +
                   `The file may be encrypted, corrupt, or contain only non-readable graphics.`,
          },
          { status: 422 }
        );
      }

      // -----------------------------------------------------------------------
      // 5. Document-level overview pairs (only when allChunkTexts is non-empty)
      // -----------------------------------------------------------------------
      if (allChunkTexts.length > 0) {
        try {
          const overviewRaw = await generateDocumentOverviewPairs(allChunkTexts, file.name);
          totalPairsGenerated += overviewRaw.length;

          const fullDocText = allChunkTexts.join(' ');

          for (const raw of overviewRaw) {
            if (isGrounded(raw.grounded_quote, fullDocText)) {
              pairsForStore.push({
                id:             uuidv4(),
                question:       raw.question,
                rephrasings:    raw.rephrasings,
                answer:         raw.answer,
                source:         file.name,
                chunk_ref:      'overview',
                grounded_quote: raw.grounded_quote,
              });
              totalPairsGrounded++;
            } else {
              console.warn(`[Upload][Grounding] Overview pair FAILED grounding check — excluded.`);
              totalPairsFailed++;
            }
          }
        } catch (e: any) {
          console.error(`[Upload] Overview generation failed for "${file.name}":`, e?.message);
        }
      } else {
        console.log(
          `[Upload] "${file.name}" — all content from vision path; ` +
          `skipping overview (no chunk texts available).`
        );
      }

      // -----------------------------------------------------------------------
      // 6. Write to FAQ store (pending)
      // -----------------------------------------------------------------------
      if (pairsForStore.length > 0) {
        addPairs(pairsForStore);
        console.log(
          `[Upload] "${file.name}" → ${pairsForStore.length} pairs written to store ` +
          `(${totalPairsFailed} failed grounding check).`
        );
      } else {
        console.warn(`[Upload] "${file.name}" → 0 pairs passed after grounding check.`);
      }
    }

    return NextResponse.json({
      message:          'Files processed. Review and approve pairs before indexing.',
      pairsGenerated:   totalPairsGenerated,
      pairsStored:      totalPairsGrounded,
      pairsFailedCheck: totalPairsFailed,
      nextStep:         'Visit the Review tab to approve pairs, then click "Index Approved Pairs".',
    });

  } catch (error: any) {
    console.error('[Upload] Error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
